
    create table tb_attachment (
        binary_id integer,
        id integer generated by default as identity,
        checksum TEXT,
        mime_type varchar(255),
        name varchar(255),
        url varchar(255),
        primary key (id)
    );

    create table tb_binary (
        id integer generated by default as identity,
        bytes varbinary(255),
        primary key (id)
    );

    create table tb_championship (
        id integer generated by default as identity,
        league_id integer,
        season_id integer,
        primary key (id)
    );

    create table tb_championship_team (
        championship_id integer,
        id integer generated by default as identity,
        team_id integer,
        primary key (id)
    );

    create table tb_country (
        id integer generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table tb_country_attachment (
        attachment_id integer,
        country_id integer unique,
        id integer generated by default as identity,
        primary key (id)
    );

    create table tb_league (
        country_id integer,
        id integer generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table tb_league_attachment (
        attachment_id integer,
        id integer generated by default as identity,
        league_id integer unique,
        primary key (id)
    );

    create table tb_match (
        attendees integer,
        away_team_goals integer,
        away_team_id integer,
        home_team_goals integer,
        home_team_id integer,
        id integer generated by default as identity,
        match_day_id integer,
        stadium_id integer,
        date timestamp(6),
        primary key (id)
    );

    create table tb_match_day (
        championship_id integer,
        id integer generated by default as identity,
        number integer,
        primary key (id)
    );

    create table tb_match_event (
        id integer generated by default as identity,
        match_id integer,
        minute_match_event integer,
        player1_id integer,
        player2_id integer,
        description varchar(255),
        type varchar(255) check (type in ('GOAL','YELLOW_CARD','RED_CARD','SUBSTITUTION')),
        primary key (id)
    );

    create table tb_placing (
        championship_id integer,
        defeats integer,
        draws integer,
        goal_difference integer,
        goals_conceded integer,
        goals_scored integer,
        id integer generated by default as identity,
        points integer,
        team_id integer,
        victories integer,
        primary key (id)
    );

    create table tb_player (
        birth_date TIMESTAMP WITHOUT TIME ZONE,
        id integer generated by default as identity,
        team_id integer,
        name varchar(255),
        nickname varchar(255),
        position varchar(255) check (position in ('GOALKEEPER','DEFENDER','MIDDLE_FIELD','FORWARD')),
        primary key (id)
    );

    create table tb_player_attachment (
        attachment_id integer,
        id integer generated by default as identity,
        player_id integer unique,
        primary key (id)
    );

    create table tb_player_stats (
        assists integer,
        championship_id integer,
        goals integer,
        id integer generated by default as identity,
        player_id integer,
        red_cards integer,
        yellow_cards integer,
        primary key (id)
    );

    create table tb_role (
        id integer generated by default as identity,
        authority varchar(255),
        primary key (id)
    );

    create table tb_season (
        id integer generated by default as identity,
        season_year integer,
        primary key (id)
    );

    create table tb_stadium (
        capacity integer,
        id integer generated by default as identity,
        latitude float(53),
        longitude float(53),
        name varchar(255),
        primary key (id)
    );

    create table tb_stadium_attachment (
        attachment_id integer,
        id integer generated by default as identity,
        stadium_id integer unique,
        primary key (id)
    );

    create table tb_team (
        id integer generated by default as identity,
        members integer,
        stadium_id integer,
        name varchar(255),
        primary key (id)
    );

    create table tb_team_attachment (
        attachment_id integer,
        id integer generated by default as identity,
        team_id integer unique,
        primary key (id)
    );

    create table tb_trophy (
        id integer generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table tb_trophy_attachment (
        attachment_id integer,
        id integer generated by default as identity,
        trophy_id integer unique,
        primary key (id)
    );

    create table tb_trophy_team (
        id integer generated by default as identity,
        quantity integer,
        team_id integer,
        trophy_id integer,
        primary key (id)
    );

    create table tb_user (
        id integer generated by default as identity,
        email varchar(255),
        name varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table tb_user_role (
        role_id integer not null,
        user_id integer not null,
        primary key (role_id, user_id)
    );

    alter table if exists tb_attachment 
       add constraint FK3qqopk5n4umrg7cqge2qv05la 
       foreign key (binary_id) 
       references tb_binary;

    alter table if exists tb_championship 
       add constraint FKq9m8oxxwglvd7gpqwnb3n8kp2 
       foreign key (league_id) 
       references tb_league;

    alter table if exists tb_championship 
       add constraint FKibbx68k8t7hscgxr82bh9f4wn 
       foreign key (season_id) 
       references tb_season;

    alter table if exists tb_championship_team 
       add constraint FKdrhw1useybmj5e93721yhep9j 
       foreign key (championship_id) 
       references tb_championship;

    alter table if exists tb_championship_team 
       add constraint FK117ule2fa541ij5q7solvbpof 
       foreign key (team_id) 
       references tb_team;

    alter table if exists tb_country_attachment 
       add constraint FKn4svn9poof0vetxxjcv50bwvs 
       foreign key (attachment_id) 
       references tb_attachment;

    alter table if exists tb_country_attachment 
       add constraint FKrkhn3xb339t7h9d7n4s6459g7 
       foreign key (country_id) 
       references tb_country;

    alter table if exists tb_league 
       add constraint FKokuiveromuujpq312a9q7pqs7 
       foreign key (country_id) 
       references tb_country;

    alter table if exists tb_league_attachment 
       add constraint FKj1j01akm8xurfrb30otxccmwg 
       foreign key (attachment_id) 
       references tb_attachment;

    alter table if exists tb_league_attachment 
       add constraint FKbndd71jgecgqwt3iqo5mmoppb 
       foreign key (league_id) 
       references tb_league;

    alter table if exists tb_match 
       add constraint FK8amnx6iojux7pv8rnfa5sc8po 
       foreign key (away_team_id) 
       references tb_team;

    alter table if exists tb_match 
       add constraint FK8i4wa361bqxlvxdrvjn556u1c 
       foreign key (home_team_id) 
       references tb_team;

    alter table if exists tb_match 
       add constraint FKn78abqkt1o8s4rcjnjrb3yjgc 
       foreign key (match_day_id) 
       references tb_match_day;

    alter table if exists tb_match 
       add constraint FK9jpeipy2ihj5t59ktueipef7q 
       foreign key (stadium_id) 
       references tb_stadium;

    alter table if exists tb_match_day 
       add constraint FK7dsjsvc0qerqsb4yha560ffno 
       foreign key (championship_id) 
       references tb_championship;

    alter table if exists tb_match_event 
       add constraint FKgxx1y0ogj4fyha0asb5amon0g 
       foreign key (match_id) 
       references tb_match;

    alter table if exists tb_match_event 
       add constraint FKdtm1xvd78k3hpwltkuy6g2sjc 
       foreign key (player1_id) 
       references tb_player;

    alter table if exists tb_match_event 
       add constraint FKefvdgk02n1rcjvxdv1sy2jku2 
       foreign key (player2_id) 
       references tb_player;

    alter table if exists tb_placing 
       add constraint FKlxarbbjhls1l4fsgcn64ovwic 
       foreign key (championship_id) 
       references tb_championship;

    alter table if exists tb_placing 
       add constraint FKcoibndmgpg8td6ix1jjrn773e 
       foreign key (team_id) 
       references tb_team;

    alter table if exists tb_player 
       add constraint FKg8y075d5qv770iffns7ijevxc 
       foreign key (team_id) 
       references tb_team;

    alter table if exists tb_player_attachment 
       add constraint FKeabr0l7i3odm2w6k4oih297u2 
       foreign key (attachment_id) 
       references tb_attachment;

    alter table if exists tb_player_attachment 
       add constraint FK9uj8lpwyaoj7wgkullfi4jl8b 
       foreign key (player_id) 
       references tb_player;

    alter table if exists tb_player_stats 
       add constraint FKi3x40j6aml6dxl3r87rln0q0 
       foreign key (championship_id) 
       references tb_championship;

    alter table if exists tb_player_stats 
       add constraint FKin8d5kb0cfo3mw8oprd6d08vf 
       foreign key (player_id) 
       references tb_player;

    alter table if exists tb_stadium_attachment 
       add constraint FK2fulifktubtp6s7ufy71uk4u5 
       foreign key (attachment_id) 
       references tb_attachment;

    alter table if exists tb_stadium_attachment 
       add constraint FKb3lgpar8an40xnjft4ojkejbu 
       foreign key (stadium_id) 
       references tb_stadium;

    alter table if exists tb_team 
       add constraint FKryqqlm3y8xsupqfsyg554d54y 
       foreign key (stadium_id) 
       references tb_stadium;

    alter table if exists tb_team_attachment 
       add constraint FK77agqruc8n6xmkurjuhajei3t 
       foreign key (attachment_id) 
       references tb_attachment;

    alter table if exists tb_team_attachment 
       add constraint FKdie0g8y9gceibkys6yxvxpf5j 
       foreign key (team_id) 
       references tb_team;

    alter table if exists tb_trophy_attachment 
       add constraint FK4byc97q2t4cuaq45ehktt3onc 
       foreign key (attachment_id) 
       references tb_attachment;

    alter table if exists tb_trophy_attachment 
       add constraint FKgwega83y93plyi5lohfgwgqau 
       foreign key (trophy_id) 
       references tb_trophy;

    alter table if exists tb_trophy_team 
       add constraint FKdqdg6b9ed508ph8cw0gc3bc7s 
       foreign key (team_id) 
       references tb_team;

    alter table if exists tb_trophy_team 
       add constraint FK9qp4fpvq2wgkt828qvr2le5f7 
       foreign key (trophy_id) 
       references tb_trophy;

    alter table if exists tb_user_role 
       add constraint FKea2ootw6b6bb0xt3ptl28bymv 
       foreign key (role_id) 
       references tb_role;

    alter table if exists tb_user_role 
       add constraint FK7vn3h53d0tqdimm8cp45gc0kl 
       foreign key (user_id) 
       references tb_user;
INSERT INTO tb_user (email, name, password) VALUES ('alex@gmail.com', 'Alex', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (email, name, password) VALUES ('maria@gmail.com', 'Maria', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (email, name, password) VALUES ('bob@gmail.com', 'Bob', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_role (authority) VALUES ( 'ROLE_CLIENT');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 2);
